# Generated by Django 3.1.2 on 2020-10-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201015_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenamiento',
            name='imagen',
            field=models.ImageField(null=True, upload_to='almacenamiento/'),
        ),
        migrations.AddField(
            model_name='almacenamiento',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fuentespoder',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fuentedepoder/'),
        ),
        migrations.AddField(
            model_name='fuentespoder',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='imagen',
            field=models.ImageField(null=True, upload_to='gabinete/'),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='imagen',
            field=models.ImageField(null=True, upload_to='gpu/'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitore',
            name='imagen',
            field=models.ImageField(null=True, upload_to='monitor/'),
        ),
        migrations.AddField(
            model_name='monitore',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='placasmadre',
            name='imagen',
            field=models.ImageField(null=True, upload_to='placasmadres/'),
        ),
        migrations.AddField(
            model_name='placasmadre',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procesadore',
            name='imagen',
            field=models.ImageField(null=True, upload_to='procesador/'),
        ),
        migrations.AddField(
            model_name='procesadore',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ram',
            name='imagen',
            field=models.ImageField(null=True, upload_to='ram/'),
        ),
        migrations.AddField(
            model_name='ram',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='almacenamiento',
            name='formato',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('HDD', 'HDD'), ('M.2', 'M.2'), ('2.5"', '2.5"')], default='s', help_text='Formato del producto', max_length=10),
        ),
        migrations.AlterField(
            model_name='almacenamiento',
            name='marca',
            field=models.CharField(help_text='Marca del producto', max_length=100),
        ),
        migrations.AlterField(
            model_name='fuentespoder',
            name='certificacion',
            field=models.CharField(choices=[('seleleccione', 'Seleccione'), ('80PLUS Gold', '80PLUS Gold'), ('80PLUS Bronze', '80PLUS Bronze'), ('Sin Certificacion', 'Sin Certificacion')], default='sele', help_text='Certificacion del producto', max_length=20),
        ),
        migrations.AlterField(
            model_name='fuentespoder',
            name='marca',
            field=models.CharField(help_text='Marca del producto', max_length=100),
        ),
        migrations.AlterField(
            model_name='fuentespoder',
            name='modular',
            field=models.CharField(choices=[('se', 'Seleccione'), ('SI', 'SI'), ('NO', 'NO')], default='se', max_length=2),
        ),
        migrations.AlterField(
            model_name='gabinete',
            name='fuente_gabinete',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('No posee', 'No posee'), ('Si posee', 'Si posee')], default='se', help_text='Posee o no posee fuente de poder dentro del gabinete', max_length=10),
        ),
        migrations.AlterField(
            model_name='gabinete',
            name='marca',
            field=models.CharField(help_text='Marca del producto', max_length=100),
        ),
        migrations.AlterField(
            model_name='gabinete',
            name='panel',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('Vidrio Templado', 'Vidrio Templado'), ('Panel Acrilico', 'Panel Acrilico')], default='s', help_text='Tipo de panel del gabinete', max_length=20),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='marca',
            field=models.CharField(help_text='Marca del producto', max_length=100),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='plataforma',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('AMD', 'AMD'), ('Nvidia', 'Nvidia')], default='s', help_text='Plataforma del producto', max_length=10),
        ),
        migrations.AlterField(
            model_name='monitore',
            name='marca',
            field=models.CharField(help_text='Marca del producto', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitore',
            name='pulgadas',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('23.0"', '23.0"'), ('24.0"', '24.0"'), ('25.0"', '25.0"'), ('26.0"', '26.0"'), ('27.0"', '27.0"')], default='sele', help_text='Pulgadas del monitor', max_length=10),
        ),
        migrations.AlterField(
            model_name='monitore',
            name='tasa_refresco',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('120 Hz', '120 Hz'), ('144 Hz', '144 Hz'), ('165 Hz', '165 Hz')], default='sel', help_text='Tasa de refresco del monitor', max_length=10),
        ),
        migrations.AlterField(
            model_name='monitore',
            name='tiempo_respuesta',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('1 ms', '1 ms'), ('2 ms', '2 ms'), ('3 ms', '3 ms'), ('4 ms', '4 ms')], default='s', help_text='Tiempo de respuesta del monitor', max_length=10),
        ),
        migrations.AlterField(
            model_name='placasmadre',
            name='formato',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('ATX', 'ATX'), ('Mini ITX', 'Mini ITX'), ('Micro ATX', 'Micro ATX')], default='s', help_text='Formato de la Placa Madre', max_length=10),
        ),
        migrations.AlterField(
            model_name='placasmadre',
            name='marca',
            field=models.CharField(help_text='Marca del producto', max_length=100),
        ),
        migrations.AlterField(
            model_name='placasmadre',
            name='plataforma',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('AMD', 'AMD'), ('Intel', 'Intel')], default='se', help_text='Plataforma de la Placa Madre', max_length=10),
        ),
        migrations.AlterField(
            model_name='procesadore',
            name='marca',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('AMD', 'AMD'), ('Intel', 'Intel')], default='s', help_text='Marca del producto', max_length=10),
        ),
        migrations.AlterField(
            model_name='procesadore',
            name='socket',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('LGA 1151-v2', 'LGA 1151-v2'), ('AM4', 'AM4'), ('TR4', 'TR4')], default='s', help_text='Socket del producto', max_length=11),
        ),
        migrations.AlterField(
            model_name='ram',
            name='marca',
            field=models.CharField(help_text='Marca del producto', max_length=100),
        ),
        migrations.AlterField(
            model_name='ram',
            name='tipo',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4')], default='se', help_text='Tipo de ram', max_length=10),
        ),
    ]
