# Generated by Django 3.1.2 on 2020-10-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20201021_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='formato',
            field=models.CharField(choices=[('seleccione', 'Seleccione'), ('DIMM', 'DIMM'), ('SO-DIMM', 'SO-DIMM')], default='s', help_text='Formato de la Ram', max_length=10),
        ),
    ]
