# Generated by Django 3.1.2 on 2020-10-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20201022_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'sugerencia'], [2, 'reclamo']])),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='placasmadre',
            name='imagen_detail',
            field=models.ImageField(null=True, upload_to='placasmadres_detail/'),
        ),
        migrations.AlterField(
            model_name='placasmadre',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
