# Generated by Django 3.1.2 on 2020-10-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20201030_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesadore',
            name='imagen_detail',
            field=models.ImageField(null=True, upload_to='procesador_detail/'),
        ),
        migrations.AlterField(
            model_name='procesadore',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
