# Generated by Django 3.1.2 on 2020-10-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20201031_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placasmadre',
            name='modelo',
            field=models.CharField(help_text='Modelo del producto', max_length=100),
        ),
        migrations.AlterField(
            model_name='placasmadre',
            name='precio',
            field=models.IntegerField(default=0, help_text='Precio del producto'),
        ),
        migrations.AlterField(
            model_name='placasmadre',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock del producto'),
        ),
        migrations.AlterField(
            model_name='procesadore',
            name='frecuencia',
            field=models.CharField(help_text='Frecuencia del producto', max_length=50),
        ),
        migrations.AlterField(
            model_name='procesadore',
            name='modelo',
            field=models.CharField(help_text='Modelo del producto', max_length=100),
        ),
        migrations.AlterField(
            model_name='procesadore',
            name='precio',
            field=models.IntegerField(default=0, help_text='Precio del producto'),
        ),
        migrations.AlterField(
            model_name='procesadore',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock del producto'),
        ),
    ]
