# Generated by Django 3.1.2 on 2020-11-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20201109_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='imagen_detail',
            field=models.ImageField(null=True, upload_to='gpu_detail/'),
        ),
    ]
