# Generated by Django 3.1.2 on 2020-11-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20201113_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuentespoder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
