# Generated by Django 3.1.2 on 2020-11-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20201115_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placasmadre',
            name='precio',
            field=models.FloatField(),
        ),
    ]
