# Generated by Django 3.1.2 on 2020-11-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20201123_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placasmadre',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
